name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
          npm install --save-dev typescript @vitest/coverage-v8
          npm audit fix || echo "Continuing despite audit issues"

      - name: Install TypeScript
        run: npm install --save-dev typescript

      - name: Typecheck
        run: npx tsc --noEmit -p tsconfig.json

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Run Prettier Check
        run: npm run prettier-check -- --write

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN_GITHUB }}" > ~/.npmrc

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}



